# Backend configuration for the CMS. Any backend will also support working with your repository locally by choosing it at the login screen.
backend:
  # The backend to use
  name: github
  # The branch to commit to. Cannot be protected
  branch: main
  # The repository from your backend to work from
  repo: snugug/monsters-and-magic
  # The domain your site is hosted on, without protocol
  site_domain: magicmonster.fun
  # The full base URL of your site, including protocol and subpath
  base_url: https://magicmonster.fun
  # The OAuth route to use for authentication. GitHub requires a backend server, or you can authenticate with a Personal Access Token directly in browser
  auth_endpoint: oauth

# The source URL to store CMS uploaded media
media_folder: public/media
# The folder where media will be served from. If your site is served from a subpath, it must be included here.
public_folder: /media

# Content collections
collections:
  - label: Standalone Page
    name: standalone
    folder: src/content/standalone
    create: true
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Body
        name: body
        widget: markdown
        required: true
  - label: Glossary Term
    name: glossary
    folder: src/content/glossary
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Type
        name: type
        widget: select
        required: false
        multiple: true
        options:
          - Condition
          - Status
          - Weapon Mastery
          - Armor Mastery
          - Weapon Property
          - Armor Property
          - Damage Type
      - label: Body
        name: body
        widget: markdown
